In [1]:
!pip install kaggle
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"parkjeongyeol","key":"2829620be97f119eda3004d8b67e9f7c"}'}

In [2]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
# Permission Warning이 발생하지 않도록 해줍니다.
!chmod 600 ~/.kaggle/kaggle.json
# 내가 참가한 대회 리스트 확인
!kaggle competitions list

ref                                            deadline             category            reward  teamCount  userHasEntered  
---------------------------------------------  -------------------  ---------------  ---------  ---------  --------------  
contradictory-my-dear-watson                   2030-07-01 23:59:00  Getting Started     Prizes         75           False  
gan-getting-started                            2030-07-01 23:59:00  Getting Started     Prizes         79           False  
store-sales-time-series-forecasting            2030-06-30 23:59:00  Getting Started  Knowledge        593           False  
tpu-getting-started                            2030-06-03 23:59:00  Getting Started  Knowledge        134           False  
digit-recognizer                               2030-01-01 00:00:00  Getting Started  Knowledge       1478           False  
titanic                                        2030-01-01 00:00:00  Getting Started  Knowledge      14640            True  
house-pr

In [3]:
!kaggle datasets download -d kneroma/tacotrashdataset

100% 2.77G/2.79G [00:36<00:00, 58.0MB/s]
100% 2.79G/2.79G [00:36<00:00, 82.7MB/s]


In [4]:
!unzip /content/tacotrashdataset.zip

Archive:  /content/tacotrashdataset.zip
  inflating: best-checkpoint-003epoch.bin  
  inflating: data/annotations.json   
  inflating: data/batch_1/000000.jpg  
  inflating: data/batch_1/000001.jpg  
  inflating: data/batch_1/000003.jpg  
  inflating: data/batch_1/000004.jpg  
  inflating: data/batch_1/000005.jpg  
  inflating: data/batch_1/000006.jpg  
  inflating: data/batch_1/000007.jpg  
  inflating: data/batch_1/000008.jpg  
  inflating: data/batch_1/000010.jpg  
  inflating: data/batch_1/000011.jpg  
  inflating: data/batch_1/000012.jpg  
  inflating: data/batch_1/000013.jpg  
  inflating: data/batch_1/000014.jpg  
  inflating: data/batch_1/000015.jpg  
  inflating: data/batch_1/000016.jpg  
  inflating: data/batch_1/000017.jpg  
  inflating: data/batch_1/000019.jpg  
  inflating: data/batch_1/000021.jpg  
  inflating: data/batch_1/000022.jpg  
  inflating: data/batch_1/000023.jpg  
  inflating: data/batch_1/000024.jpg  
  inflating: data/batch_1/000025.jpg  
  inflating: data/ba

In [5]:
!pip install pycocotools

In [6]:
# import os
# import numpy as np
# import torch
# from PIL import Image
# from pycocotools.coco import COCO

# data_source = COCO(annotation_file = '/content/data/annotations.json')

# def Image_contain(root):

#   imgs = []

#   for i in range(1, 15+1):
    
#     imgs_root = root + f'batch_{i}'

#     imgs_root = glob(imgs_root + '*.jpg')

#     for j in imgs_root:




# class ImageProcess(torch.uttils.datta.Dataset):
#   def __init__(self, root, transforms):
#     self.root = root
#     self.transform = transforms



In [7]:
# from glob import glob
# os.chdir('/content/data')


# def image_collection(root = None):
#   imgs_path = []
#   for i in range(1, 15 + 1):
#     a = []
#     if len(glob(f'batch_{i}' +'/' +'*.jpg')) == 0:
#       imgs_path.append(glob(root+f'batch_{i}' + '/' + '*.JPG'))

#     else:
#       imgs_path.append(glob(root+f'batch_{i}' + '/' + '*.jpg'))

#   imgs = []
#   for i in imgs_path:
#     for j in i:
#       imgs.append(j)

#   return imgs

## Faster RCNN

In [8]:
!git clone https://github.com/wimlds-trojmiasto/detect-waste.git

Cloning into 'detect-waste'...
remote: Enumerating objects: 928, done.
remote: Counting objects: 100% (162/162), done.
remote: Compressing objects: 100% (126/126), done.
remote: Total 928 (delta 71), reused 80 (delta 36), pack-reused 766
Receiving objects: 100% (928/928), 85.18 MiB | 21.24 MiB/s, done.
Resolving deltas: 100% (437/437), done.


In [9]:
import numpy as np
import os
os.chdir('/content/detect-waste/FastRCNN')
import torch
import pycocotools
import torch.utils.data
from PIL import Image
import pandas as pd
import torchvision
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
from engine import train_one_epoch, evaluate
import utils
import transforms as T
from PIL import ImageDraw
import os.path as path
import re
import json

In [10]:
def parse_one_annot(path_to_data_file, filename):
    data = pd.read_csv(path_to_data_file)
    print(filename)
    boxes_array = data[data["filename"] == filename][["xmin", "ymin",        
    "xmax", "ymax"]].values
    print(boxes_array)
    return boxes_array

In [11]:
def getListOfFiles(dirName):
    listOfFile = os.listdir(dirName)
    allFiles = list()
    for entry in listOfFile:
        fullPath = os.path.join(dirName, entry)
        if os.path.isdir(fullPath):
            allFiles = allFiles + getListOfFiles(fullPath)
        else:
                fullPath = fullPath.replace(data_folder, '')
                allFiles.append(fullPath)  
    return allFiles

In [12]:
class Dataset(torch.utils.data.Dataset):
    def __init__(self, root, data_file, transforms=None):
        self.root = root
        self.transforms = transforms
        files = getListOfFiles(os.path.join(root))
        p = re.compile('batch')
        l2 = [ s for s in files if p.match(s) ]
        self.imgs = sorted(l2)
        self.path_to_data_file = data_file
    def __getitem__(self, idx):
        img_path = os.path.join(self.root, self.imgs[idx])
        self.imgs[idx] = self.imgs[idx]
        img = Image.open(img_path).convert("RGB")
        box_list = parse_one_annot(self.path_to_data_file, self.imgs[idx])
        boxes = torch.as_tensor(box_list, dtype=torch.float32)
        num_objs = len(box_list)
        labels = torch.ones((num_objs,), dtype=torch.int64)
        image_id = torch.tensor([idx])
        area = (boxes[:, 3] - boxes[:, 1]) * (boxes[:, 2] - boxes[:,0])
        iscrowd = torch.zeros((num_objs,), dtype=torch.int64)
        target = {}
        target["boxes"] = boxes
        target["labels"] = labels
        target["image_id"] = image_id
        target["area"] = area
        target["iscrowd"] = iscrowd
        if self.transforms is not None:
                 img, target = self.transforms(img, target)
        return img, target
    
    def __len__(self):
        return len(self.imgs)

In [13]:
def get_model(num_classes):
    model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
    in_features = model.roi_heads.box_predictor.cls_score.in_features
    model.roi_heads.box_predictor = FastRCNNPredictor(in_features,num_classes)
    return model

In [14]:
def get_transform(train):
    transforms = []
    transforms.append(T.ToTensor())
    if train:
        transforms.append(T.RandomHorizontalFlip(0.5))
    return T.Compose(transforms)

## CSV 파일 만들기

In [15]:
data_file = '/content/data/annot.csv'
json_path = '/content/data/annotations.json'
annot_folder = '/content/data'
with open(json_path) as json_file: 
    data = json.load(json_file)

In [16]:
def export_data(data, dtype, file):
    img = data[dtype] 
    data_file = open(file, 'w') 
    csv_writer = csv.writer(data_file) 
    count = 0
    for i in img: 
        if count == 0: 
            header = i.keys() 
            csv_writer.writerow(header) 
            count += 1
        csv_writer.writerow(i.values()) 
    data_file.close()

In [17]:
import csv
export_data(data, 'images', os.path.join(annot_folder,'data_file.csv'))
export_data(data, 'annotations', os.path.join(annot_folder,'data_file2.csv'))
export_data(data, 'categories', os.path.join(annot_folder,'data_file3.csv'))

In [18]:
data3 = pd.read_csv(os.path.join(annot_folder,'data_file3.csv'))
data2 = pd.read_csv(os.path.join(annot_folder,'data_file2.csv'))
data = pd.read_csv(os.path.join(annot_folder,'data_file.csv'))

In [19]:
data = data.rename(columns={"id": "image_id"})
data3 = data3.rename(columns={"id": "category_id"})
data2 = data2.merge(data, on='image_id', how='left')
data2 = data2.merge(data3, on='category_id', how='left')
data2 = data2.rename(columns={"supercategory": "class"})
data2 = data2.rename(columns={"file_name": "filename"})
data2['bbox'] = data2['bbox'].map(lambda x: x.lstrip('[').rstrip(']'))
data2[['xmin','ymin','xmax','ymax']] = data2.bbox.str.split(",",expand=True,)

In [20]:
data2['xmax'] = data2['xmax'].astype(float) + data2['width'].astype(float)
data2['ymax'] = data2['ymax'].astype(float) + data2['height'].astype(float)

In [21]:
data2 = data2[['filename','width','height','class','xmin','ymin','xmax','ymax']]
data2.to_csv(data_file,index=False)

In [22]:
data_folder = '/content/data/'
data_file = '/content/data/annot.csv'
working_dir = '/content/detect-waste/FastRCNN'
num_classes = 28

dataset = Dataset(root= data_folder, data_file= data_file , transforms = get_transform(train=True))
dataset_test = Dataset(root= data_folder, data_file= data_file , transforms = get_transform(train=False))

torch.manual_seed(1)
indices = torch.randperm(len(dataset)).tolist()
testing_num = int(len(dataset)*0.2)
dataset = torch.utils.data.Subset(dataset, indices[:-testing_num])
dataset_test = torch.utils.data.Subset(dataset_test, indices[-testing_num:])
data_loader = torch.utils.data.DataLoader(
              dataset, batch_size=2, shuffle=True, num_workers=4,
              collate_fn=utils.collate_fn)
data_loader_test = torch.utils.data.DataLoader(
         dataset_test, batch_size=1, shuffle=False, num_workers=4,
         collate_fn=utils.collate_fn)
print("We have: {} examples, {} are training and {} testing".format(len(indices), len(dataset), len(dataset_test)))

We have: 1500 examples, 1200 are training and 300 testing


In [23]:
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
model = get_model(num_classes)
model.to(device)
params = [p for p in model.parameters() if p.requires_grad]
optimizer = torch.optim.SGD(params, lr=0.005,
                            momentum=0.9, weight_decay=0.0005)
lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer,
                                       step_size=3,gamma=0.1)

Downloading: "https://download.pytorch.org/models/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth" to /root/.cache/torch/hub/checkpoints/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth


  0%|          | 0.00/160M [00:00<?, ?B/s]

In [24]:
num_epochs = 10
for epoch in range(num_epochs):
    train_one_epoch(model, optimizer, data_loader, device, epoch, print_freq=10)
    lr_scheduler.step()
    evaluate(model, data_loader_test, device=device)

batch_15/000020.jpg
[[ 980.  734. 2310. 1869.]
 [1091.  967. 2100. 1616.]
 [  39.  433. 2251. 1627.]]
batch_6/000032.JPG
batch_2/000026.JPG
[[ 424. 1378. 3408. 2577.]
 [ 720.  915. 3435. 2587.]
 [1973.  957. 3398. 2576.]
 [3194.  964. 3333. 2542.]
 [3147.  999. 3348. 2534.]
 [2617.  907. 3542. 2628.]][[ 951. 1516. 3501. 2604.]
 [2202. 1638. 3520. 2549.]
 [ 360. 1917. 3369. 2509.]
 [1316. 1943. 3373. 2546.]]

batch_14/000090.jpg
[[1073. 1935. 3163. 4357.]]
batch_1/000091.JPG
[[   0.  414. 5454. 4049.]
 [2593.  914. 3846. 2889.]]
batch_8/000061.jpg
[[ 562.  801. 1297. 1794.]
 [ 917.    0. 1226. 1617.]
 [ 678.  718. 1225. 1666.]]
batch_13/000074.jpg
[[ 915.  318. 5909. 5290.]]
batch_8/000034.jpg
[[1747.  538. 2603. 3408.]
 [2321. 2300. 2543. 3305.]
 [1503.  944. 2488. 3288.]
 [  50. 1684. 2509. 3304.]
 [ 430. 1855. 2472. 3312.]
 [ 968. 2200. 2513. 3309.]
 [1116. 2041. 2524. 3338.]
 [1335. 2430. 2574. 3388.]
 [   4. 1786. 2488. 3307.]]
batch_12/000085.jpg
[[1939.6667 3258.0476 3546.     47

/usr/local/lib/python3.7/dist-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
 [2385. 1985. 3075. 4133.]
 [ 342. 1948. 3071. 4068.]
 [1798. 2113. 3112. 4116.]
 [1463. 1882. 3044. 4082.]
 [1765. 2067. 3058. 4093.]]
batch_15/000010.jpg
[[2781. 2216. 3101. 4112.]
 [2720. 2220. 3087. 4100.]
 [ 891. 2433. 3125. 4132.]
 [ 679. 2591. 3126. 4136.]
 [ 738. 2684. 3133. 4141.]
 [ 598. 1024. 3880. 4816.]
 [2525. 3113. 3065. 4080.]
 [ 333. 1448. 3171. 4106.]]
batch_15/000011.jpg
[[1445. 2076. 3278. 4546.]
 [2654.  697. 3108. 4066.]]
batch_15/000012.jpg
[[1304. 2103. 3271. 4254.]
 [ 943. 1855. 3171. 4210.]]
batch_15/000013.jpg
[[ 790. 2243. 3541. 4573.]
 [ 868. 2309. 3104. 4090.]
 [1529. 3422. 3143. 4159.]
 [1550. 3218. 3465. 4528.]
 [1565. 3652. 3230. 4199.]
 [ 714.  865. 3201. 4162.]
 [ 512.  789. 3181. 4107.]]
batch_15/000014.jpg
[[1338. 1411. 2532. 3736.]]
batch_15/000015.jpg
[[ 703. 1417. 3384. 2595.]
 [ 715.  860. 3319. 2474.]
 [1304.  879. 3371. 2484.]
 [1210. 1013. 3369. 2510.]
 [2920. 1124. 3338. 2507.]
 [2924. 1166. 3282. 2466.]
 

In [31]:
model_path = '/content/drive/MyDrive/인공지능 그랜드 챌린지/model.h5'

torch.save(model.state_dict(), model_path)

In [33]:
loaded_model = get_model(num_classes = num_classes)
loaded_model.load_state_dict(torch.load(model_path))

<All keys matched successfully>

In [34]:
idx = 1
img, _ = dataset_test[idx]
label_boxes = np.array(dataset_test[idx][1]["boxes"])
loaded_model.eval()
with torch.no_grad():
    prediction = loaded_model([img])
image = Image.fromarray(img.mul(255).permute(1, 2,0).byte().numpy())
draw = ImageDraw.Draw(image)
for elem in range(len(label_boxes)):
    draw.rectangle([(label_boxes[elem][0], label_boxes[elem][1]),
    (label_boxes[elem][2], label_boxes[elem][3])], 
    outline ="green", width =3)
for element in range(len(prediction[0]["boxes"])):
    boxes = prediction[0]["boxes"][element].cpu().numpy()
    score = np.round(prediction[0]["scores"][element].cpu().numpy(),
                    decimals= 4)
    if score > 0.8:
        draw.rectangle([(boxes[0], boxes[1]), (boxes[2], boxes[3])], 
        outline ="red", width =3)
        draw.text((boxes[0], boxes[1]), text = str(score))
image

batch_3/IMG_4887.JPG
[[ 974. 1074. 2651. 3397.]
 [ 828. 1652. 2537. 3321.]]
batch_3/IMG_4887.JPG
[[ 974. 1074. 2651. 3397.]
 [ 828. 1652. 2537. 3321.]]
